### ISSUE TITLE
Add JS Linting & Review Initial Setup

### ISSUE THREAD

**Issue by sixlive** [sixlive/primer#3]
## To Do
- [ ] Update files (see below)
- [ ] Initial lint and fixes on JS files
- [ ] Review initial dependencies (e.g. should lodash be required initially?)
- [ ] Review global `window` vars, this may not be required
- [x] Review additional StandardJS rules – Was able to implement standard config
- [x] Determine if `eslint-plugin-jsx-a11y` and `eslint-plugin-react` are actually needed (stole when prototyping with airbnb) – They weren't
- [x] Figure out a clean way to run on mix watch (see below)

## File Updates

`package.json` updates

```json
{
  "scripts": {
        "style:lint": "eslint resources/assets/js --ext .js,.vue",
        "style:fix": "eslint resources/assets/js --ext .js,.vue --fix"
  },
  "devDependencies": {
        "eslint": "^4.11.0",
        "eslint-config-standard": "^10.2.1",
        "eslint-loader": "^1.9.0",
        "eslint-plugin-import": "^2.8.0",
        "eslint-plugin-node": "^5.2.1",
        "eslint-plugin-promise": "^3.6.0",
        "eslint-plugin-standard": "^3.0.1",
        "eslint-plugin-vue": "next",
  }
}
```

`.eslintrc.js`

```javascript
module.exports = {
  extends: [
    'standard',
    'plugin:vue/recommended',
  ],
  env: {
    'es6': true,
    'node': true,
    'browser': true
  },
  plugins: [
    'import',
    'promise',
    'vue'
  ],
  rules: {
    "no-console": [2, { allow: ["warn", "error"] }]
  },
  'overrides': [
    {
      'files': ['*.vue', '**/*.vue'],
      'rules': {
        'indent': 'off'
      }
    }
  ]
}

```

`.drone.yml`

```yaml
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret

pipeline:
  build_php:
    group: build_test
    image: composer
    commands:
      - composer install --prefer-dist
      - vendor/bin/php-cs-fixer fix --dry-run --diff

  build_node:
    group: build_test
    image: node:8
    commands:
      - npm i -g yarn
      - yarn
      - yarn development

  dependency_check:
    image: sixlive/core-php
    commands:
      - vendor/bin/security-checker security:check

  phpunit:
    image: sixlive/core-php
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PORT=3306
      - DB_PASSWORD=secret
      - DB_DATABASE=laravel
    commands:
      - sleep 15
      - touch .env
      - vendor/bin/phpunit

  build_php_production:
    group: build_production
    when:
      branch: master
      event: tag
      status: success
    image: composer
    commands:
      - rm -rf vendor
      - composer install --prefer-dist --no-dev --optimize-autoloader
      - php artisan route:cache
      # - php artisan config:cache

  build_node_production:
    group: build_production
    when:
      branch: master
      event: tag
      status: success
    image: node:8
    commands:
      - yarn production
      - rm -rf node_modules
```

## Additional Webpack Config

`webpack.mix.js`

```javascript
mix.webpackConfig({
  module: {
    rules: [
      {
        test: /\.js|\.vue$/,
        loader: "eslint-loader"
      },
    ],
  },
})
```
